<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.zhaopin.uitest.cases.LoginIHR" tests="2" time="77.136" ignored="4" failures="0" timestamp="06 Mar 2018 06:08:11 GMT" skipped="1" hostname="xuyaovs-PC" errors="1">
  <testcase name="loginIhr" time="46.481" classname="com.zhaopin.uitest.cases.LoginIHR">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.zhaopin.uitest.base.Locator$3.apply(Locator.java:346)
	at com.zhaopin.uitest.base.Locator$3.apply(Locator.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
	at com.zhaopin.uitest.base.Locator.elementIsDisplay(Locator.java:343)
	at com.zhaopin.uitest.base.Locator.getElement(Locator.java:280)
	at com.zhaopin.uitest.base.Locator.click(Locator.java:91)
	at com.zhaopin.uitest.cases.LoginIHR.loginIhr(LoginIHR.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- loginIhr -->
  <testcase name="loginIhr" time="30.655" classname="com.zhaopin.uitest.cases.LoginIHR">
    <skipped/>
  </testcase> <!-- loginIhr -->
  <testcase name="afterTest" classname="com.zhaopin.uitest.base.TestBase">
    <skipped/>
  </testcase> <!-- afterTest -->
  <testcase name="beforeTest" classname="com.zhaopin.uitest.base.TestBase">
    <skipped/>
  </testcase> <!-- beforeTest -->
  <testcase name="afterSuite" classname="com.zhaopin.uitest.base.TestBase">
    <skipped/>
  </testcase> <!-- afterSuite -->
  <testcase name="beforeSuite" classname="com.zhaopin.uitest.base.TestBase">
    <skipped/>
  </testcase> <!-- beforeSuite -->
</testsuite> <!-- com.zhaopin.uitest.cases.LoginIHR -->
